spring:
  datasource:
    url: jdbc:h2:mem:library
  sql:
    init:
      schema-locations: schema.sql
      data-locations: data.sql
      mode: always

  jpa:
    generate-ddl: false
    show-sql: false

    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: INFO
